import type { InstallTarget, RuntimeId, ToolManifestItem } from "./types";

const githubProxy = "https://gh.llkk.cc";
const npmmirror = "https://registry.npmmirror.com";

function source(
  id: string,
  label: string,
  kind: ToolManifestItem["sources"][number]["kind"],
  url: string,
  priority: number,
  regionHint: ToolManifestItem["sources"][number]["regionHint"] = "global",
) {
  return { id, label, kind, url, priority, regionHint };
}

export const toolManifest: ToolManifestItem[] = [
  {
    id: "python",
    label: "Python 3.11 x64",
    category: "runtime",
    requiredFor: ["codex-cli", "claude-cli"],
    defaultVersion: "3.11.x",
    win7Version: "3.8.x",
    policy: "system-shared",
    detectionCommands: ["python --version", "py -3 --version"],
    installNotes: "Python 默认作为系统共用运行时。Win10/11 推荐 3.11 x64，Win7 自动降级到 3.8 兼容线。",
    sources: [
      source("python-official", "Python 官方下载", "official", "https://www.python.org/downloads/windows/", 20),
      source("python-mirror", "npmmirror Python 镜像", "custom", `${npmmirror}/-/binary/python/`, 10, "china-mainland"),
      source("python-offline", "离线缓存", "offline-cache", "offline://python", 1, "offline"),
    ],
  },
  {
    id: "node",
    label: "Node.js LTS 隔离运行时",
    category: "runtime",
    requiredFor: ["codex-cli", "claude-cli", "cc-switch", "codex-plus-plus"],
    defaultVersion: "22 LTS",
    win7Version: "16.x portable",
    policy: "isolated",
    detectionCommands: ["node --version", "npm --version"],
    installNotes: "Node 默认安装到工具箱隔离目录，启动 Codex/Claude 时临时注入 PATH，不污染用户原有环境。",
    sources: [
      source("node-npmmirror", "npmmirror Node 二进制镜像", "npm-mirror", `${npmmirror}/-/binary/node/`, 10, "china-mainland"),
      source("node-official", "Node 官方下载", "official", "https://nodejs.org/dist/", 20),
      source("node-offline", "离线缓存", "offline-cache", "offline://node", 1, "offline"),
    ],
  },
  {
    id: "git",
    label: "Git for Windows",
    category: "runtime",
    requiredFor: ["codex-cli", "claude-cli"],
    defaultVersion: "latest",
    policy: "system-shared",
    detectionCommands: ["git --version"],
    installNotes: "Git 用于拉取源码、同步 skill 和 GitHub 提交。优先复用系统安装。",
    sources: [
      source("git-proxy", "GitHub 加速镜像", "github-proxy", `${githubProxy}/https://github.com/git-for-windows/git/releases/latest`, 10, "china-mainland"),
      source("git-github", "Git for Windows Release", "github-release", "https://github.com/git-for-windows/git/releases/latest", 20),
    ],
  },
  {
    id: "powershell",
    label: "PowerShell 7",
    category: "runtime",
    requiredFor: ["codex-cli", "claude-cli"],
    defaultVersion: "7.x",
    win7Version: "5.1 built-in",
    policy: "optional",
    detectionCommands: ["pwsh --version", "$PSVersionTable.PSVersion"],
    installNotes: "高级脚本使用 PowerShell 7；Win7 保留系统 PowerShell 5.1 并给出兼容提示。",
    sources: [
      source("powershell-proxy", "PowerShell GitHub 加速", "github-proxy", `${githubProxy}/https://github.com/PowerShell/PowerShell/releases/latest`, 10, "china-mainland"),
      source("powershell-github", "PowerShell Release", "github-release", "https://github.com/PowerShell/PowerShell/releases/latest", 20),
    ],
  },
  {
    id: "vcpp-runtime",
    label: "Visual C++ 运行库",
    category: "system",
    requiredFor: ["codex-desktop", "claude-desktop", "codex-plus-plus", "cc-switch"],
    defaultVersion: "2015-2022",
    policy: "system-shared",
    detectionCommands: ["reg query HKLM\\SOFTWARE\\Microsoft\\VisualStudio\\14.0\\VC\\Runtimes\\x64"],
    installNotes: "许多桌面端和原生模块依赖 VC++ 运行库，缺失时会在安装前补齐。",
    sources: [
      source("vcpp-official", "Microsoft VC++ Redistributable", "official", "https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist", 10),
    ],
  },
  {
    id: "webview2",
    label: "Microsoft Edge WebView2 Runtime",
    category: "system",
    requiredFor: ["codex-plus-plus", "cc-switch", "codex-desktop", "claude-desktop"],
    defaultVersion: "evergreen",
    win7Version: "not supported",
    policy: "system-shared",
    detectionCommands: ["reg query HKCU\\Software\\Microsoft\\EdgeUpdate\\Clients", "reg query HKLM\\Software\\Microsoft\\EdgeUpdate\\Clients"],
    installNotes: "Win10/11 Tauri 主版本依赖 WebView2。Win7 版本改用 Electron，不强依赖 WebView2。",
    sources: [
      source("webview2-official", "WebView2 Evergreen Runtime", "official", "https://developer.microsoft.com/microsoft-edge/webview2/", 10),
    ],
  },
  {
    id: "tls-certs",
    label: "TLS 证书与网络探测",
    category: "system",
    requiredFor: ["codex-cli", "claude-cli"],
    defaultVersion: "system",
    policy: "optional",
    detectionCommands: ["curl --version", "certutil -urlcache *"],
    installNotes: "用于检查 HTTPS 证书链、代理和镜像源连通性。不会修改系统证书，除非用户明确选择修复。",
    sources: [source("system", "系统内置", "official", "system://tls", 10)],
  },
  {
    id: "codex-cli",
    label: "Codex CLI",
    category: "agent",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "system-shared",
    detectionCommands: ["codex --version"],
    installNotes: "支持复用官方桌面版自带 CLI 或独立 CLI，配置目录保持在用户主目录 .codex。",
    sources: [
      source("codex-official", "OpenAI Codex 官方渠道", "official", "https://openai.com/codex/", 10),
    ],
  },
  {
    id: "codex-desktop",
    label: "Codex 桌面版",
    category: "agent",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "system-shared",
    detectionCommands: ["where codex"],
    installNotes: "默认用户级安装，安装完成后创建桌面快捷方式。",
    sources: [
      source("codex-desktop-official", "Codex Desktop 官方渠道", "official", "https://openai.com/codex/", 10),
    ],
  },
  {
    id: "codex-plus-plus",
    label: "Codex++",
    category: "manager",
    requiredFor: ["codex-cli", "codex-desktop"],
    defaultVersion: "latest",
    policy: "system-shared",
    detectionCommands: ["reg query HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall /s /f Codex++"],
    installNotes: "选择 Codex 时默认安装 Codex++ 管理增强，并保留 .codex 配置位置。",
    sources: [
      source("codexpp-proxy", "Codex++ GitHub 加速", "github-proxy", `${githubProxy}/https://github.com/BigPizzaV3/CodexPlusPlus/releases/latest`, 10, "china-mainland"),
      source("codexpp-github", "BigPizzaV3/CodexPlusPlus", "github-release", "https://github.com/BigPizzaV3/CodexPlusPlus/releases/latest", 20),
    ],
  },
  {
    id: "claude-cli",
    label: "Claude Code 终端版",
    category: "agent",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "system-shared",
    detectionCommands: ["claude --version"],
    installNotes: "Claude CLI 默认通过 npm/官方渠道安装，配置写入 .claude/settings.json。",
    sources: [
      source("claude-npmmirror", "npmmirror", "npm-mirror", `${npmmirror}/@anthropic-ai/claude-code`, 10, "china-mainland"),
      source("claude-npm", "npm 官方包", "official", "https://www.npmjs.com/package/@anthropic-ai/claude-code", 20),
    ],
  },
  {
    id: "claude-desktop",
    label: "Claude 桌面版",
    category: "agent",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "system-shared",
    detectionCommands: ["reg query HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall /s /f Claude"],
    installNotes: "可选安装；失败时不会阻塞 Claude CLI 与 CC Switch 配置。",
    sources: [
      source("claude-desktop-official", "Claude 官方下载", "official", "https://claude.ai/download", 10),
    ],
  },
  {
    id: "cc-switch",
    label: "CC Switch",
    category: "manager",
    requiredFor: ["claude-cli", "claude-desktop"],
    defaultVersion: "latest",
    policy: "system-shared",
    detectionCommands: ["reg query HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall /s /f \"CC Switch\""],
    installNotes: "选择 Claude 时默认安装 CC Switch，服务商和模型写入 .cc-switch 配置。",
    sources: [
      source("ccswitch-proxy", "CC Switch GitHub 加速", "github-proxy", `${githubProxy}/https://github.com/farion1231/cc-switch/releases/latest`, 10, "china-mainland"),
      source("ccswitch-github", "farion1231/cc-switch", "github-release", "https://github.com/farion1231/cc-switch/releases/latest", 20),
    ],
  },
  {
    id: "pnpm",
    label: "pnpm",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["pnpm --version", "corepack pnpm --version"],
    installNotes: "专家模式可选，用于更快安装 Node 包。",
    sources: [source("pnpm-npm", "npm 包", "npm-mirror", `${npmmirror}/pnpm`, 10, "china-mainland")],
  },
  {
    id: "yarn",
    label: "Yarn",
    category: "helper",
    requiredFor: [],
    defaultVersion: "stable",
    policy: "optional",
    detectionCommands: ["yarn --version", "corepack yarn --version"],
    installNotes: "专家模式可选包管理器。",
    sources: [source("yarn-npm", "npm 包", "npm-mirror", `${npmmirror}/yarn`, 10, "china-mainland")],
  },
  {
    id: "uv",
    label: "uv",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["uv --version"],
    installNotes: "专家模式可选 Python 包管理器。",
    sources: [
      source("uv-proxy", "uv GitHub 加速", "github-proxy", `${githubProxy}/https://github.com/astral-sh/uv/releases/latest`, 10, "china-mainland"),
      source("uv-github", "uv Release", "github-release", "https://github.com/astral-sh/uv/releases/latest", 20),
    ],
  },
  {
    id: "pipx",
    label: "pipx",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["pipx --version"],
    installNotes: "专家模式可选 Python CLI 隔离安装工具。",
    sources: [source("pipx-pypi", "PyPI 镜像", "custom", "https://pypi.tuna.tsinghua.edu.cn/simple/pipx/", 10, "china-mainland")],
  },
  {
    id: "github-cli",
    label: "GitHub CLI",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["gh --version"],
    installNotes: "用于创建仓库、发布 Release 和自动提交源码。",
    sources: [
      source("gh-proxy", "GitHub CLI 加速", "github-proxy", `${githubProxy}/https://github.com/cli/cli/releases/latest`, 10, "china-mainland"),
      source("gh-github", "GitHub CLI Release", "github-release", "https://github.com/cli/cli/releases/latest", 20),
    ],
  },
  {
    id: "sevenzip",
    label: "7-Zip",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["7z"],
    installNotes: "用于解压 portable 运行时和离线缓存包。",
    sources: [source("sevenzip-official", "7-Zip 官方下载", "official", "https://www.7-zip.org/download.html", 10)],
  },
  {
    id: "winget",
    label: "winget",
    category: "helper",
    requiredFor: [],
    defaultVersion: "system",
    policy: "optional",
    detectionCommands: ["winget --version"],
    installNotes: "Win10/11 可选系统包管理器，国内网络不可用时自动回退到镜像和离线缓存。",
    sources: [source("winget-system", "系统内置", "official", "system://winget", 10)],
  },
  {
    id: "scoop",
    label: "Scoop",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["scoop --version"],
    installNotes: "专家模式可选用户级包管理器。",
    sources: [source("scoop-github", "Scoop 官方", "github-release", "https://github.com/ScoopInstaller/Scoop", 20)],
  },
  {
    id: "chocolatey",
    label: "Chocolatey",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["choco --version"],
    installNotes: "专家模式可选系统包管理器，需要管理员权限时会明确提示。",
    sources: [source("choco-official", "Chocolatey 官方", "official", "https://chocolatey.org/install", 20)],
  },
  {
    id: "bun",
    label: "Bun",
    category: "helper",
    requiredFor: [],
    defaultVersion: "latest",
    policy: "optional",
    detectionCommands: ["bun --version"],
    installNotes: "可选 JS 运行时，默认不作为 Codex/Claude 必需项。",
    sources: [
      source("bun-proxy", "Bun GitHub 加速", "github-proxy", `${githubProxy}/https://github.com/oven-sh/bun/releases/latest`, 10, "china-mainland"),
      source("bun-github", "Bun Release", "github-release", "https://github.com/oven-sh/bun/releases/latest", 20),
    ],
  },
];

export function getRequiredRuntimesForTargets(targets: InstallTarget[]) {
  return toolManifest.filter((tool) =>
    tool.requiredFor.some((target) => targets.includes(target)),
  );
}

export function getManifestItem(id: RuntimeId | InstallTarget) {
  return toolManifest.find((tool) => tool.id === id);
}
